gallerie/urls.py
from django.urls import path
from . import views

app_name = 'gallerie'

urlpatterns = [
    path('', views.all_galleries, name='all_galleries'),
    path('', views.all_galleries, name='all_galleries'),
]

perso/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('gallerie/', include('gallerie.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallerie/models.py
from django.db import models


class Gallerie(models.Model):
    titre = models.CharField(max_length=250)
    image = models.ImageField(upload_to='gallerie/images/')
    date = models.DateField()

project/models.py
from django.db import models


class Project(models.Model):
    titre = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='project/images/')

gallerie/views.py
from django.shortcuts import render
from .models import Gallerie


def all_galleries(request):
    galleries = Gallerie.objects.order_by('-date')
    return render(request, 'gallerie/all_galleries.html', {'galleries': galleries})

project/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    projects = Project.objects.all()
    return render(request, 'project/home.html', {'projects': projects})

gallerie/templates/gallerie/all_galleries.html
{% load static %}

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static "project/joe.css" %}">
    <title>{% block title %}GALLERIE{% endblock %}</title>
</head>
<body>
<header>
    <nav>
        <ul class="menu">
            <li ><a href="{% url 'home' %}">HOME</a></li>
            <li class="active"><a href="{% url 'gallerie:all_galleries' %}">GALLERIE</a></li>
        </ul>
    </nav>
    <div class="bvn">
        <h1>BIENVENUE</h1>
    </div>
    <div class="zone">
        <p>dans la zone</p>
    </div>
</header>
<div class="proj">
    {% for gallerie in galleries %}
    <div>
        <img src="{{ gallerie.image.url }}" class="imag" alt="gallerie-images">
        <h2 class="tex">{{ gallerie.titre }}</h2>
        <p class="tex pad">{{ gallerie.date }}</p>
    </div>
{% endfor %}
</div>
</body>
<footer>
    <div class="info">
        <div class="pro">
            <h4>bassanejoseph@gmail.com</h4>
            <p>+228 92602849</p>
        </div>
        <div class="pro">
            <h4>DESIGN by</h4>
            <p>@warriorgraphic</p>
        </div>
        <div class="pro">
            <h4>TOUT DROIT RESERVE</h4>
            <p>copyright 2020</p>
        </div>
    </div>
</footer>
</html>

project/templates/project/home.html
{% load static %}

<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static "project/joe.css" %}">
    <title>{% block title %}HOME{% endblock %}</title>
</head>
<body>
<header>
    <nav>
        <ul class="menu">
            <li class="active"><a href="{% url 'home' %}">HOME</a></li>
            <li><a href="{% url 'gallerie:all_galleries' %}">GALLERIE</a></li>
        </ul>
    </nav>
    <div class="bvn">
        <h1>BIENVENUE</h1>
    </div>
    <div class="zone">
        <p>dans la zone</p>
    </div>
</header>

<section class="service">
    <h1 class="tex tit">SERVICES</h1>
    <div class="services">
        <div class="ser">
            <h1 class="description">WEB <br>DESIGN</h1>
            <p>Site web responsive</p>
            <p>Classement SEO pour vos site</p>
            <p>Redaction de contenue</p>
        </div>
        <div class="ser">
            <h1 class="description">SOFTWARE <br> DESIGN</h1>
            <p>Application mobile </p>
            <p>Application de bureau</p>
            <p>Application multiplatforme</p>
        </div>
        <div class="ser">
            <h1 class="description">GRAPHIC <br>DESIGN</h1>
            <p>Logo design</p>
            <p>Identité visuelle</p>
            <p>Packging</p>
            <p>Design général</p>
        </div>
    </div>
</section>

<section class="mesprojets">
    <div class="tit">
        <h2>MES PROJETS</h2>
    </div>
    <div class="prj">
        {% for project in projects %}
        <div>
            <img src="{{ project.image.url }}" class="ima" alt="image-project">
            <h1 class="tex">{{ project.titre }}</h1>
            <p class="tex pad" >{{ project.description }}</p>
        </div>
        {% endfor %}
    </div>
</section>
</body>
<footer>
    <div class="info">
        <div class="pro">
            <h4>bassanejoseph@gmail.com</h4>
            <p>+228 92602849</p>
        </div>
        <div class="pro">
            <h4>DESIGN by</h4>
            <p>@warriorgraphic</p>
        </div>
        <div class="pro">
            <h4>TOUT DROIT RESERVE</h4>
            <p>copyright 2020</p>
    </div>
    </div>
</footer>
</html>